# Generated by Django 5.0.7 on 2024-08-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("categories", models.ManyToManyField(to="store.category")),
            ],
        ),
    ]
