# Generated by Django 5.0.7 on 2024-08-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
